version: '3.7'
services:
  symbolscraper:
    container_name: mmda-sscraper
    build:
      context: ../..
      dockerfile: pipeline/docker/parsers/symbolscraper/Dockerfile

  layoutparser:
    container_name: mmda-layoutparser
    environment:
      MODEL_CONFIG: lp://efficientdet/PubLayNet,lp://efficientdet/MFD
    build:
      context: ../..
      dockerfile: pipeline/docker/predictors/layoutparser/Dockerfile

  vila:
    container_name: mmda-vila
    build:
      context: ../..
      dockerfile: pipeline/docker/predictors/vila/Dockerfile
      args:
        MODEL_CONFIG: pipeline/vila-model-weights

  python:
    container_name: mmda
    build:
      context: ../..
      dockerfile: pipeline/docker/Dockerfile
