config_version: 0.0.1
model_variants:
  vila:
    # Class path to pydantic Instance implementation in <model_package_name>==<model_package_version>
    instance: ai2_internal.timo.vila.interface.Instance

    # Class path to pydantic Prediction implementation in <model_package_name>==<model_package_version>
    prediction: ai2_internal.timo.vila.interface.Prediction

    # Class path to Predictor implementation in <model_package_name>==<model_package_version>
    predictor: ai2_internal.timo.vila.interface.Predictor

    # Class path to pydantic PredictorConfig implementation in <model_package_name>==<model_package_version>
    predictor_config: ai2_internal.timo.vila.interface.PredictorConfig

    # Any additional sets of dependencies required by the model.
    # These are the 'extras_require' keys in your setup.py.
    extras_require: ["dev", "vila_predictors"]

    # Full S3 path to tar.gz'ed artifacts archive, nullable
    artifacts_s3_path: s3://ai2-timo-registry/model-artifacts/vila/v0.tar.gz

    # Version of python required for model runtime, e.g. 3.7, 3.8, 3.9
    python_version: 3.8

    cuda: False

    integration_test: ai2_internal.timo.vila.integration_test.TestInterfaceIntegration

    # One or more bash commands to execute as part of a RUN step in a Dockerfile.
    # Leave this unset unless your model has special system requirements beyond
    # those in your setup.py.
    docker_run_commands: ["apt-get update", "apt-get install python3-opencv -y"]

