name: MMDA CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.8"]
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Test with Python ${{ matrix.python-version }}
        run: | 
          pip install -e .[dev]
          pytest tests --ignore=tests/test_predictors/test_vila_predictors.py

      - name: Test VILA Predictors
        run: | 
          pip install -e .[vila_predictors]
          pytest tests/test_predictors/test_vila_predictors.py